name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Test on node@${{ matrix.node }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Enable Corepack 🔧
        run: npx corepack enable
      - name: Setup node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install 🪄
        run: yarn install --frozen-lockfile
      - name: Lint 🔍
        run: yarn run lint
      - name: Prettier 🔍
        run: yarn run prettycheck
      - name: TypeScript 🔍
        run: yarn run typecheck
      - name: Jest 🔍
        run: yarn run spec
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Build on node@${{ matrix.node }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Enable Corepack 🔧
        run: npx corepack enable
      - name: Setup node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install 🪄
        run: yarn install --frozen-lockfile
      - name: Build 💎
        run: yarn run build
